#163756376 Create Login Functionality
andela/Titan-Devs pull request #13
Opened 2019-02-07 15:00 UTC by YvesIraguha

#### What does this PR do?
Creates login functionality
#### Description of Task to be completed?
* Create `POST : /api/v1/users/login` route
* Create tests for `POST : /api/v1/users/login` route
* Create validation of login credentials. 
* Create login controller. 
#### How should this be manually tested?
* Fetch the branch `ft-user-can-login-163756376`
* Checkout the branch `ft-user-can-login-163756376`
* Setup your database. 
* Run tests `yarn run test`
* Start the server `yarn run server`
* Create a user `POST: /api/v1/users` with `email, password, and username`
* Consume the endpoint `POST: /api/v1/users/login ` with `email and password` using Postman client. 
* You should see a successfull login message. 
#### What are the relevant pivotal tracker stories?
163756376

2019-02-07 15:38 UTC, Musigwa-zz approved these changes
I have seen your work, It is actually clean and descriptive. However, you forgot to mention how to set up the database, but more than that everything is clean.

2019-02-08 09:10 UTC, espoirMur requested changes

2019-02-08 09:10 UTC, espoirMur commented on controllers/auth/login.controller.js
> +import models from "../../models";
@YvesIraguha is this the file naming convention we agree on??

2019-02-08 09:10 UTC, espoirMur commented on controllers/auth/login.controller.js
> +import jwt from "jsonwebtoken";
Are we using Jwt?? or PassportJwt ???? @YvesIraguha

2019-02-11 13:22 UTC, espoirMur approved these changes

2019-02-11 13:24 UTC, merged