#163518689 Create the new article
andela/Titan-Devs pull request #19
Opened 2019-02-14 06:16 UTC by Musigwa

#### What does this PR do?
- It helps the logged in user to create his/her new article
#### Description of Task to be completed?
- Secure the endpoint with JsonWebToken (created the checkAuth middleware)
- Create the request handler of the article creation endpoint
#### How should this be manually tested?
- After cloning the repository, check out `ft-create-article-endpoints-163518689` branch
- Make sure to read `README.md` file to get the setup instructions
- Create the user using the instructions found in `README.md` under `API Spec` subtitle
- Login with the credentials of the registered user. Make sure to follow the instructions in `README.md`
- The successful login will return the access `token`, copy it to be used while creating an article
- Create an article following the instructions. After the successful article creation, you should get back the article information. with the successful message.

#### Any background context you want to provide?
I have moved the following: `signup.test.js` and `login.test.js` files into `tests/integration` directory to have a clean structure.
#### What are the relevant pivotal tracker stories?
- #163518689

2019-02-14 12:01 UTC, espoirMur requested changes

2019-02-14 12:01 UTC, espoirMur commented on middlewares/checkAuth.js
> +      return res.status(INTERNAL_SERVER_ERROR).json({ message: "Access denied" });
@Musigwa, Bro "Access denied" is not meaningful to users!
You may add 'you are not authorized to perform this action'.

2019-02-14 12:01 UTC, espoirMur commented on middlewares/checkAuth.js
> +      return res.status(INTERNAL_SERVER_ERROR).json({ message: "Access denied" });
you can check [this ](https://softwareengineering.stackexchange.com/a/185715/281564)for more information about errors messages

2019-02-14 12:01 UTC, espoirMur commented on middlewares/checkAuth.js
> +      return res.status(INTERNAL_SERVER_ERROR).json({ message: "Access denied" });
And I think passport has better option for protecting routes check with @abayo-luc !

2019-02-14 12:01 UTC, espoirMur commented on tests/integration/article.test.js
> +import chaiHttp from "chai-http";
@Musigwa, bro!
It looks like this feature is not heavily tested.
Would you consider adding more test cases?
Eg : 
- what happens when you are creating an article and title is not provided?
- what happens when you are creating a post and body is not provided?
- what happens when you are creating a post and description is not provided?
- what result are you expecting after creating a post?

2019-02-14 14:58 UTC, espoirMur approved these changes

2019-02-14 16:43 UTC, niomwungeri-fabrice requested changes
Please return list tags in create article response @Musigwa

2019-02-14 17:01 UTC, niomwungeri-fabrice approved these changes

2019-02-18 15:01 UTC, abayo-luc commented
Your migration are causing issue, especially when someone is trying to run ```sequelize db:migrate:undo```

2019-02-19 05:33 UTC, merged