#163518690 User should be able to rate articles
andela/Titan-Devs pull request #20
Opened 2019-02-14 20:24 UTC by espoirMur

#### What does this PR do?
This PR adds the functionality of creating, updating, fetching rating on a given article

#### Description of Task to be completed?
- add create rating endpoint 
- add get all rating endpoint
- add update rating endpoint
- secure all endpoints with Jwt

#### How should this be manually tested?
* Open Postman client
* Consume the API:
    * `post: /api/v1/article/:id/rating` supply the user 's token,and number of rating.
    * `put: /api/v1/article/:articleId/rating/:ratingId` supply the user 's token, and the updated rate.
    * `get: api/v1/article/:id/ratingId` supply the user 's token.

2019-02-15 06:39 UTC, YvesIraguha approved these changes

2019-02-19 21:38 UTC, YvesIraguha reviewed
Please, resolve the conflicts in the conflicting files. 
`controllers/auth/loginController.js`
`controllers/users.js`
`index.js`
`middlewares/checkAuth.js`
`middlewares/passport.js`
`models/Article.js`
`routes/articles.js`
`routes/index.js`
`sample.env`
`swagger.json`
`tests/integration/article.test.js`
`tests/integration/login.test.js`
`tests/integration/signup.test.js`

2019-02-20 09:28 UTC, puritybirir commented on controllers/articles.js
> +      // console.log("DATABASE ERROR:", error);
Nitpick: no-console

2019-02-20 09:28 UTC, puritybirir commented on index.js
>  // catch 404 and forward to error handler
Remove this comment

2019-02-20 09:28 UTC, puritybirir commented on controllers/ratings.js
> +          .query('SELECT * FROM "ratings"  WHERE "articleId" =:articleId', {
Use sequelize and not raw SQL queries

2019-02-20 09:28 UTC, puritybirir commented on middlewares/passport.js
> + * @description - The middleware to check for authentication. It checks on every
Remain with only the first part of the description

2019-02-20 09:28 UTC, puritybirir commented on routes/ratings.js
> +    // pass the user to the next middleware
Remove inline comment

2019-02-20 15:03 UTC, abayo-luc requested changes

2019-02-20 15:03 UTC, abayo-luc commented on controllers/auth/loginController.js
>  /** Define class for handling user login */
use JsDoc comment

2019-02-20 15:03 UTC, abayo-luc commented on controllers/ratings.js
> +            // check if the error is related to the post id not find in table
Remove these comments

2019-02-20 15:03 UTC, abayo-luc commented on controllers/ratings.js
> +    const articleId = req.params.id;
use ```slug``` instead of ```id```

2019-02-20 15:03 UTC, abayo-luc commented on controllers/ratings.js
> +        Rating.create({ articleId, userId, rating })
are you saving ```rating``` directly from the request body? I think you should be saving an average or something?

2019-02-20 15:03 UTC, abayo-luc commented on controllers/ratings.js
> +  static update(req, res, next) {
I don't this updating ```rating``` is necessary.

2019-02-22 13:48 UTC, puritybirir requested changes

2019-02-22 13:48 UTC, puritybirir commented on controllers/ratingsController.js
> +class RatingController {
Add space here

2019-02-22 13:48 UTC, puritybirir commented on tests/integration/rating.test.js
> +import dotenv from "dotenv";
Use the format for testing used by the rest of the team

2019-02-25 08:44 UTC, abayo-luc requested changes
- Improve your test coverage
- Rebase develop
- Remove comments in the codebase. If it will take you to add some configuration to .eslintric, feel free and communicate to the team. 
- I wasn't able to rate an article, I don't know why it kept giving me error ```The page you are looking for cannot be found```, yet I am sure I have created an article.

2019-02-25 08:44 UTC, abayo-luc commented on controllers/ratingsController.js
> +            /* eslint-disable no-underscore-dangle */
Remove this comment!

2019-02-25 08:44 UTC, abayo-luc commented on controllers/ratingsController.js
> +              [sequelize.fn("AVG", sequelize.col("rating")), "averageRating"]
What does this do?

2019-02-25 14:56 UTC, abayo-luc approved these changes

2019-02-26 09:33 UTC, puritybirir approved these changes

2019-02-26 09:34 UTC, merged

2019-03-01 10:36 UTC, espoirMur commented
> * Improve your test coverage
> * Rebase develop
> * Remove comments in the codebase. If it will take you to add some configuration to .eslintric, feel free and communicate to the team.
> * I wasn't able to rate an article, I don't know why it kept giving me error `The page you are looking for cannot be found`, yet I am sure I have created an article.

2019-03-01 10:36 UTC, espoirMur commented
Thanks, @abayo-luc  let me do that...

2019-03-01 10:38 UTC, espoirMur commented
> * Improve your test coverage
> * Rebase develop
> * Remove comments in the codebase. If it will take you to add some configuration to .eslintric, feel free and communicate to the team.
> * I wasn't able to rate an article, I don't know why it kept giving me the error `The page you are looking for cannot be found`, yet I am sure I have created an article.

Thanks, @abayo-luc  for that, Let me fix it...