163518693 User Follow Each Other
andela/Titan-Devs pull request #23
Opened 2019-02-14 21:56 UTC by abayo-luc

#### What does this PR do?
Enable user to follow auther
#### Description of Task to be completed?
```POST /api/v1/profiles/:username/follow```
```DELETE /api/v1/profiles/:username/follow```
```GET /api/v1/profiles/:username/followers```
```GET /api/v1/profiles/:username/followings```
#### How should this be manually tested?
-Clone the repo and checkout `ft-user-follow-each-other-163518693` branch
- Using any `API client tool(usually POSTMAN)`,
- Create the user and login to get the `access-token`
- Make request to the above end point with existing ```username```
- Make sure to pass the token under `request headers`. It should be {`Authorization`: `Bearer <access-token>`} KEY, VALUE PAIR
#### Any background context you want to provide?
before running anything, ensure packages are updated ```yarn``` and no pending migration ```sequelize db:migrate```
#### What are the relevant pivotal tracker stories?
163518693

2019-02-15 05:53 UTC, YvesIraguha approved these changes

2019-02-15 10:30 UTC, puritybirir requested changes

2019-02-15 10:30 UTC, puritybirir commented on controllers/followerController.js
> +/** Define the class for creating the profile
Use JSDoc better. Follow standard set by Musigwa

2019-02-15 10:30 UTC, puritybirir commented on controllers/profileController.js
> +console.log(User);
Remove console.log when making pull request

2019-02-15 10:30 UTC, puritybirir commented on sample.env
> +<<<<<<< HEAD
Why are there merge conflicts in this file?

2019-02-15 10:30 UTC, puritybirir commented on tests/users/follower.test.js
> +
Use consistent spacing

2019-02-18 08:20 UTC, abayo-luc commented
Duplicated

2019-02-18 08:20 UTC, closed without merging