User can share on article on social media 163518700
andela/Titan-Devs pull request #29
Opened 2019-02-19 10:59 UTC by niomwungeri-fabrice

#### What does this PR do?
Share article on different social media including email
#### Description of Task to be completed?
Have this endpoints work
EndPoints:
* `GET /article/:articleId/share/twitter` for sharing on twitter.
* `GET /article/:articleId/share/fb` for sharing on facebook.
* `GET /article/:articleId/share/email` for sharing on email.
#### How should this be manually tested?
* Fetch the branch `ft-user-can-share-163518700`
* Checkout the branch `ft-user-can-share-163518700`
* Setup your database. 
* Run tests `yarn run test`
* Start the server `yarn run server`
* Create a user `POST: /api/v1/users` with `email, password, and username`
* Login a user `POST: /api/v1/auth/login` with `email and password` you will get a token
* Pass token to header and access one of the above endpoint in PR description
#### What are the relevant pivotal tracker stories?
163518700

2019-02-19 11:12 UTC, abayo-luc requested changes
we have two controllers doing exactly the same thing, ```./controller/articles.js``` and ```./controller/articlesController.js```

2019-02-19 11:12 UTC, abayo-luc commented on controllers/articles.js
> +        // eslint-disable-next-line no-restricted-syntax
remove these comments by eslint.

2019-02-19 11:22 UTC, niomwungeri-fabrice commented on controllers/articles.js
> +        // eslint-disable-next-line no-restricted-syntax
@abayo-luc Done!

2019-02-19 15:22 UTC, Musigwa-zz requested changes
The whole work looks great however, I can't see the swagger documentation and the jsDoc comments.
Please consider documenting your API.

2019-02-20 07:01 UTC, abayo-luc approved these changes

2019-02-20 08:48 UTC, puritybirir commented on controllers/articlesController.js
> +
jsdoc comments

2019-02-20 10:08 UTC, closed without merging