[#163518683] fix failing test
andela/Titan-Devs pull request #32
Opened 2019-02-19 16:01 UTC by niomwungeri-fabrice

#### What does this PR do?
Email verification 
#### Description of Task to be completed?
After a user has been created successfully the platform sends the email via email,
the user is able to click on the link in order to get access to other services like creating an article.
The is an option of resending the email if the email wasn's sent on time.
EndPoints:
* `POST api/v1/users` for creating an account to the system, and receive a verification email.
* `GET api/v1/users/confirm/:auth_token` for email verification.
* `PUT api/v1/users/resend` for resending email verification.
#### How should this be manually tested?
* Fetch the branch `ft-user-get-verification-link-163518683`
* Checkout the branch `ft-user-get-verification-link-163518683`
* Setup your database. 
* Run tests `yarn run test`
* Start the server `yarn run server`
* Create a user `POST: /api/v1/users` with `email, password, and username`
* Go to your email click on the `verify my email` which was sent while registering it will trigger this endPoint `GET api/v1/users/confirm/:auth_token` using Postman client. 
* You should see a User verified successfully. 
* If the email didn't come you could use this endpoint to resend the email `PUT api/v1/users/resend` you only provide email as follow:
`
{
	"email":"example@gmail.com"
}
`
#### What are the relevant pivotal tracker stories?
163518683

2019-02-19 21:36 UTC, YvesIraguha approved these changes

2019-02-20 10:01 UTC, puritybirir requested changes

2019-02-20 10:01 UTC, puritybirir commented on controllers/usersController.js
>     *
Add description to comments

2019-02-20 10:01 UTC, puritybirir commented on controllers/usersController.js
> +
JSDoc comments

2019-02-20 10:01 UTC, puritybirir commented on controllers/usersController.js
> +      if (!email) return res.status(404).json({ message: "Email is required" });
Incorrect status code. 404 is for not found

2019-02-20 10:01 UTC, puritybirir commented on controllers/usersController.js
> +      if (!email) return res.status(404).json({ message: "Email is required" });
Invalid data should be a 400

2019-02-20 10:01 UTC, puritybirir commented on controllers/usersController.js
> +        return res.status(404).json({ message: "Invalid email" });
use constants file for the status code

2019-02-20 10:01 UTC, puritybirir commented on controllers/usersController.js
> +          message: "User already verified!"
Message should be : User verified

2019-02-20 10:01 UTC, puritybirir commented on controllers/usersController.js
> +
JSDoc comments

2019-02-20 10:01 UTC, puritybirir commented on migrations/20190219113957-add-isVerified-to-user.js
> +      Add altering commands here.
Remove comments

2019-02-20 10:01 UTC, puritybirir commented on tests/integration/emailConfirmation.test.js
> +    expect(results.status).equal(404);
Use correct status codes

2019-02-22 08:55 UTC, espoirMur requested changes

2019-02-22 08:55 UTC, espoirMur commented on controllers/usersController.js
> +        .json({ message: "Sending email failed", errors: error.stack });
Why sending error.stack to the user??

2019-02-22 08:55 UTC, espoirMur commented on controllers/usersController.js
> +        .status(INTERNAL_SERVER_ERROR)
Same thing here, why sending errors.stack to the user?

2019-02-22 08:55 UTC, espoirMur commented on tests/helpers/testData.js
> +    email: "fabrice.niyomwungeri@andela.com",
don't share your email on GitHub please, you may get spammed by hacker...

2019-02-22 08:55 UTC, espoirMur commented on tests/integration/comment.test.js
> +                  console.log(res.status);
Thanks, @houndci-bot !! Good Job.

2019-02-22 09:16 UTC, puritybirir approved these changes

2019-02-22 09:21 UTC, espoirMur approved these changes

2019-02-22 09:25 UTC, merged