163518692 User Can Like Article
andela/Titan-Devs pull request #36
Opened 2019-02-20 12:52 UTC by abayo-luc

#### What does this PR do?
Let authenticated user like an article or dislike an arleady liked article
#### Description of Task to be completed?
- Write tests for article likes
- The article like and dislike
- Fetch article with likes
#### How should this be manually tested?
- Clone the repo and  check out `ft-article-likes-dislike-163518692` branch
- Follow the instructions in `ReadMe`
- Using any `API client tool *POSTMAN*`,
- Create the user and login to get the ```POST /api/v1/users``` and ```POST /api/v1/users/login```
- Create an article using ```POST /api/v1/articles``` and get the ```slug```
- Access `POST /api/v1/articles/:slug/likes` endpoint for liking an article
- Access ```DELETE /api/v1/articles/:slug/likes``` endpoint for disliking the article
- Make sure to pass the token under `request headers`. It should be {`Authorization`: `Bearer <access-token>`} KEY, VALUE PAIR
- Access ```GET /api/v1/articles/:slug``` to fetch article with its likes
#### Any background context you want to provide?
Trying to like article twice, cancel the first like. 
#### What are the relevant pivotal tracker stories?
#163518692

2019-02-20 16:30 UTC, Musigwa commented on controllers/articlesController.js
> +  /**
Good description, please do the same in the rest of your files to keep consistency

2019-02-20 16:32 UTC, Musigwa commented on controllers/articleLikesController.js
> +   *
Please remove the unwanted space to keep consistency.

2019-02-20 16:49 UTC, Musigwa-zz requested changes
The work actually looks great, but please consider going through the files and change JsDoc, spacing to meet the team's consistency.

2019-02-20 16:49 UTC, Musigwa commented on controllers/articleLikesController.js
> +      return res.status(202).json({ message: "Successfully disliked" });
@abayo-luc, can state the reason for using **`202`** status code?
According to the following ==> `https://httpstatuses.com/202`, **`202`** means the request has been accepted for processing, but the processing has not been completed.

2019-02-20 16:49 UTC, Musigwa commented on tests/integration/articleLikes.test.js
> +      });
Can you please try to keep a single space between the test suits to keep consistency?

2019-02-20 21:49 UTC, Musigwa commented
> Some files could not be reviewed due to errors:
> 
> Oops! Something went wrong! :(
> ESLint: 4.19.1.
> ESLint couldn't find the plugin "eslint-plugin-jsdoc". This can happen for a couple different reasons:
> 1. If ESLint is installed globally, then make sure eslint-plugin-jsdoc is also installed globally. A globally-installed ESLint cannot find a locally-installed plugin.
> 2. If ESLint is installed locally, then it's likely that the plugin isn't installed correctly. Try reinstalling by running the following:
>     npm i eslint-plugin-jsdoc@latest --save-dev
> If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.

2019-02-21 07:42 UTC, Musigwa commented
abayo-luc, as reported by CodeClimate, the overall coverage was reduced by (-4%). Would you please consider covering all possible statements in your tests?
<img width="299" alt="screen shot 2019-02-21 at 09 37 49" src="https://user-images.githubusercontent.com/29999424/53151860-cbc01e00-35bc-11e9-8f0c-c00d6f487aa3.png">
<img width="698" alt="screen shot 2019-02-21 at 09 34 31" src="https://user-images.githubusercontent.com/29999424/53151885-d8447680-35bc-11e9-8ad4-0d7d1e0ad17d.png"> Your branch's coverage.
<img width="726" alt="screen shot 2019-02-21 at 09 42 10" src="https://user-images.githubusercontent.com/29999424/53151938-fd38e980-35bc-11e9-99dd-f2d28604c6f0.png"> The develop branch's coverage.

2019-02-21 11:13 UTC, Musigwa-zz approved these changes
Looks great after testing it locally.

2019-02-21 12:24 UTC, espoirMur requested changes

2019-02-21 12:24 UTC, espoirMur commented on .eslintrc
> -  "plugins": ["prettier", "jsdoc", "eslint-plugin-jsdoc"],
Why removing these plugins???

2019-02-21 13:43 UTC, espoirMur approved these changes

2019-02-22 07:28 UTC, merged